### ISSUE TITLE
Reorganise the module

### ISSUE THREAD

**Issue by claudiu-cristea** [ec-europa/rdf_entity#17]
The main thing this module is providing, the most important file, is `RdfEntitySparqlStorage` and the entity query. If I'm asked what this module does and I have to use only one phrase, I would say:

> Provides an entity storage class that allows an arbitrary Drupal content entity to use a SPARQL backend. Period.

Form this perspective the `rdf_entity` entity type is only a use-case of this module. Given all these, I'm proposing:

1. The `rdf_entity` should be moved into a separate sub-module. It can be used directly or only as a good example.
1. The main module should be renamed. Probably to `rdf_storage`?
1. All references to applications that are using this module should be removed.
1. Fix & Move the webprofiler logic in a submodule to be enabled only on dev environments

**Comment by sandervd** [comment]
Ow, yes!
Let's come up with a sexy name for this 😃

**Comment by claudiu-cristea** [comment]
> Let's come up with a sexy name for this 

@sandervd `rdf_storage`?

**Comment by claudiu-cristea** [comment]
This should include also #14.

**Comment by claudiu-cristea** [comment]
@sandervd  As the main functionality of the module is the **SPARQL entity storage/query** I would go with `sparql_entity_storage` (or `sparql_storage`?)

**Comment by claudiu-cristea** [comment]
Decided for `sparql_entity_storage` will keep the history (git filter-branch). `rdf_entity` will live in a separate project keeping the whole history.
